version: "3.9"
services:
  product-app:
    image: mikhailmi/product-app:master
    container_name: product-app
    hostname: product-app
    ports:
      - "127.0.0.1:8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev-network
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres:13
    hostname: product-postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      POSTGRES_DB: product
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U product -d product" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:

networks:
  dev-network:
    driver: bridge