server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product

  sql:
    init:
      schema-locations: classpath:schema-all.sql
      mode: always

  batch:
    jdbc:
      initialize-schema: always